# platform :ios, '9.0'

target 'PrevenT' do


 source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

#pod 'SwiftHTTP', '~> 3.0.1'



source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
pod 'GoogleMaps'
pod 'Google/CloudMessaging'
pod 'Alamofire', '~> 4.7'
pod 'Alamofire-Synchronous', '~> 4.0'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
pod 'Kingfisher', '~> 4.0'

end
